# Generated by Django 5.2.1 on 2025-06-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('channel_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Telegram Канал',
                'verbose_name_plural': 'Telegram Каналы',
                'db_table': 'telegram_channels',
            },
        ),
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.BigIntegerField(blank=True, null=True)),
                ('pars_text', models.TextField(blank=True, null=True)),
                ('ai_text', models.TextField(blank=True, null=True)),
                ('url_image', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('is_post', models.BooleanField(blank=True, default=False, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.telegramchannel', to_field='channel_id')),
            ],
            options={
                'verbose_name': 'Новость (новая)',
                'verbose_name_plural': 'Новости (новые)',
                'db_table': 'post_news',
            },
        ),
        migrations.CreateModel(
            name='UserChannelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.telegramchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешение пользователя на канал',
                'verbose_name_plural': 'Разрешения пользователей на каналы',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
